// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: casbin.sql

package db

import (
	"context"
)

const listCasbinPolicyRules = `-- name: ListCasbinPolicyRules :many
SELECT v0, v1, v2 FROM casbin_rules WHERE ptype = 'p'
`

type ListCasbinPolicyRulesRow struct {
	V0 *string
	V1 *string
	V2 *string
}

// Lists the `p` (policy) rows from the global casbin_rules table for the
// authorizer to load. casbin_rules carries no tenant_id and is deliberately
// outside RLS (it is the same role -> (resource, action) mapping for every
// tenant), so this runs on the BYPASSRLS pool: the load is a system-level,
// tenant-less operation, and on the regular RLS-bound pool it would trip the
// missing-tenant warning. Only v0..v2 are selected because the v1 model is
// (sub, obj, act) -- a three-field `p` rule -- so v3..v5 are always null here.
func (q *Queries) ListCasbinPolicyRules(ctx context.Context) ([]ListCasbinPolicyRulesRow, error) {
	rows, err := q.db.Query(ctx, listCasbinPolicyRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCasbinPolicyRulesRow
	for rows.Next() {
		var i ListCasbinPolicyRulesRow
		if err := rows.Scan(&i.V0, &i.V1, &i.V2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
