// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const loadAggregateEvents = `-- name: LoadAggregateEvents :many
SELECT id, tenant_id, aggregate_id, aggregate_type, sequence, stream_position,
       event_type, payload, metadata, occurred_at
FROM events
WHERE aggregate_id = $1
ORDER BY sequence
`

// Backs EventStore.Load (US-03.03, AC3): every event for one aggregate in
// sequence order. Runs on the RLS-bound pool (opengate_app) -- the command path
// loads an aggregate's history before deciding the next command, with the tenant
// already bound, so RLS scopes the read to the caller's tenant. ORDER BY sequence
// gives the deterministic 1-based replay order the aggregate rebuild depends on,
// served by the events_aggregate_sequence_unique index (aggregate_id, sequence).
func (q *Queries) LoadAggregateEvents(ctx context.Context, aggregateID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, loadAggregateEvents, aggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AggregateID,
			&i.AggregateType,
			&i.Sequence,
			&i.StreamPosition,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readEventsAfterPosition = `-- name: ReadEventsAfterPosition :many
SELECT id, tenant_id, aggregate_id, aggregate_type, sequence, stream_position,
       event_type, payload, metadata, occurred_at
FROM events
WHERE stream_position > $1
ORDER BY stream_position
LIMIT $2
`

type ReadEventsAfterPositionParams struct {
	StreamPosition int64
	Limit          int32
}

// Backs EventStore.ReadAfterPosition: events whose stream_position is strictly
// greater than a cursor, in global (monotonic) order, capped by a limit. Runs on
// the BYPASSRLS pool (opengate_bypass) -- projector workers walk the whole store
// across tenants from a saved cursor, so no tenant is bound. The strict `>` plus
// ORDER BY stream_position makes the scan gap-free and resumable, served by the
// events_stream_position_idx index. The LIMIT is the projector's page size; sqlc
// names it Limit, which the adapter fills from the port's `limit int`.
func (q *Queries) ReadEventsAfterPosition(ctx context.Context, arg ReadEventsAfterPositionParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, readEventsAfterPosition, arg.StreamPosition, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AggregateID,
			&i.AggregateType,
			&i.Sequence,
			&i.StreamPosition,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readTenantEventsInTimeRange = `-- name: ReadTenantEventsInTimeRange :many
SELECT id, tenant_id, aggregate_id, aggregate_type, sequence, stream_position,
       event_type, payload, metadata, occurred_at
FROM events
WHERE tenant_id = $1
  AND occurred_at >= $2
  AND occurred_at <= $3
ORDER BY occurred_at, stream_position
`

type ReadTenantEventsInTimeRangeParams struct {
	TenantID uuid.UUID
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

// Backs EventStore.ReadByTenantAndTimeRange: one tenant's events within an
// INCLUSIVE [from, to] time window (System Design §2), in deterministic
// chronological order. Runs on the BYPASSRLS pool (opengate_bypass) -- the export
// capability names the tenant explicitly via sqlc.arg(tenant_id) rather than
// taking it from RLS context. Both bounds are inclusive (occurred_at >= from_time
// AND occurred_at <= to_time). The bounds use named args (from_time/to_time)
// because the column occurred_at is referenced twice: positional params would
// emit an OccurredAt/OccurredAt_2 field pair, whereas the named args yield clean,
// self-documenting FromTime/ToTime fields (from/to alone are reserved SQL words).
// The (occurred_at, stream_position) sort breaks ties on identical timestamps so
// the export is reproducible, served by the events_tenant_occurred_at_idx index.
func (q *Queries) ReadTenantEventsInTimeRange(ctx context.Context, arg ReadTenantEventsInTimeRangeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, readTenantEventsInTimeRange, arg.TenantID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AggregateID,
			&i.AggregateType,
			&i.Sequence,
			&i.StreamPosition,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
