// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CasbinRule struct {
	ID    int32
	Ptype string
	V0    *string
	V1    *string
	V2    *string
	V3    *string
	V4    *string
	V5    *string
}

type CommandIdempotencyKey struct {
	TenantID        uuid.UUID
	IdempotencyKey  string
	RequestHash     []byte
	ResponseStatus  int32
	ResponseHeaders []byte
	ResponseBody    []byte
	CreatedAt       pgtype.Timestamptz
}

type DecisionIdempotencyKey struct {
	TenantID       uuid.UUID
	IdempotencyKey string
	Decision       string
	ReasonCode     string
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
}

type Event struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	AggregateID    uuid.UUID
	AggregateType  string
	Sequence       int64
	StreamPosition int64
	EventType      string
	Payload        []byte
	Metadata       []byte
	OccurredAt     pgtype.Timestamptz
	InsertXid      pgtype.Uint64
}

type ProjectionProgress struct {
	ProjectorName   string
	LastPosition    int64
	LastEventAt     pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	LastConsumedXid pgtype.Uint64
}

type ReconciliationIdempotencyKey struct {
	TenantID   uuid.UUID
	ReaderID   uuid.UUID
	SequenceNo int64
	EventID    uuid.UUID
	CreatedAt  pgtype.Timestamptz
}

type Session struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	UserID       uuid.UUID
	TokenHash    []byte
	Role         string
	IssuedAt     pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	IssuedFromIp *netip.Addr
	UserAgent    *string
}

type Tenant struct {
	ID             uuid.UUID
	Name           string
	ContactEmail   *string
	Timezone       string
	SessionTimeout pgtype.Interval
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Slug           string
}

type User struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	Email              string
	PasswordHash       string
	Role               string
	Status             string
	LastLoginAt        pgtype.Timestamptz
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
