// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	UserID       uuid.UUID
	TokenHash    []byte
	Role         string
	IssuedAt     pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	IssuedFromIp *netip.Addr
	UserAgent    *string
}

type Tenant struct {
	ID             uuid.UUID
	Name           string
	ContactEmail   *string
	Timezone       string
	SessionTimeout pgtype.Interval
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Slug           string
}

type User struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	Email              string
	PasswordHash       string
	Role               string
	Status             string
	LastLoginAt        pgtype.Timestamptz
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
