// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"
	"net/netip"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, tenant_id, user_id, token_hash, role,
    issued_at, last_seen_at, expires_at, issued_from_ip, user_agent
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateSessionParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	UserID       uuid.UUID
	TokenHash    []byte
	Role         string
	IssuedAt     pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	IssuedFromIp *netip.Addr
	UserAgent    *string
}

// Pre-authentication session insert (login). Runs on the BYPASSRLS pool because
// login is the authentication act itself — no tenant context exists yet. Every
// value is supplied by the caller: the Step 4 use case mints the id and token,
// hashes the token, snapshots the role, and computes expires_at from the
// tenant's session_timeout. No security-relevant column is defaulted in SQL —
// the caller is the single source of truth for the row's contents.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.Role,
		arg.IssuedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.IssuedFromIp,
		arg.UserAgent,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE id = $1 AND tenant_id = $2
`

type DeleteSessionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

// Post-authentication logout (System Design §7 convention): regular RLS-bound
// pool, tenant taken from context by the adapter and passed as $2. The
// `tenant_id = $2` predicate is the same belt-and-suspenders scoping as
// RefreshSession (see the note above) — the only tenant scoping until US-02.05's
// RLS lands, and cheap defense-in-depth after. Do NOT remove it. :execrows so
// logout can distinguish "deleted" from "already gone."
func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT id, tenant_id, user_id, role, issued_at, last_seen_at, expires_at
FROM sessions
WHERE token_hash = $1
`

type FindSessionByTokenHashRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	UserID     uuid.UUID
	Role       string
	IssuedAt   pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

// Pre-authentication session lookup, run before the tenant context exists: the
// cookie carries only the opaque token, so the lookup is by the globally-unique
// token_hash and the tenant_id is READ FROM the matched row (it cannot be an
// input — it is the output). Runs on the BYPASSRLS pool; the adapter does NOT
// call tenant.FromContext. token_hash is deliberately NOT selected back out: it
// is never needed after the lookup, and not returning it keeps the secret
// material out of logs and structs. No row -> the adapter maps pgx.ErrNoRows to
// ports.ErrSessionNotFound.
func (q *Queries) FindSessionByTokenHash(ctx context.Context, tokenHash []byte) (FindSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findSessionByTokenHash, tokenHash)
	var i FindSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.IssuedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const refreshSession = `-- name: RefreshSession :execrows
UPDATE sessions
SET last_seen_at = $1, expires_at = $2
WHERE id = $3 AND tenant_id = $4
`

type RefreshSessionParams struct {
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ID         uuid.UUID
	TenantID   uuid.UUID
}

// Post-authentication sliding-window refresh (System Design §7 convention). By
// the time this runs, the middleware has validated the session and set the
// tenant context, so the adapter executes it on the regular RLS-bound pool and
// takes the tenant from context, passing it as $4.
//
// The `tenant_id = $4` predicate is BELT-AND-SUSPENDERS, not redundant noise —
// do NOT "simplify" it away. (a) RLS does not exist until US-02.05, so until
// then this explicit predicate is the ONLY tenant scoping on the write. (b) Once
// RLS lands, the explicit predicate and the policy agree, and the redundancy is
// cheap defense-in-depth — the dual-layer philosophy (System Design §10). The
// `id = $3` predicate is the primary key. :execrows lets the caller detect
// "zero rows updated" — a session that vanished, or a tenant mismatch.
func (q *Queries) RefreshSession(ctx context.Context, arg RefreshSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, refreshSession,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.ID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
