// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const resolveTenantBySlug = `-- name: ResolveTenantBySlug :one
SELECT id, status, session_timeout
FROM tenants
WHERE slug = $1
`

type ResolveTenantBySlugRow struct {
	ID             uuid.UUID
	Status         string
	SessionTimeout pgtype.Interval
}

// Pre-authentication tenant resolution (System Design §10 carve-out). The slug
// arrives from the URL path segment and IS how the tenant is discovered, so no
// tenant context exists yet; the adapter runs this on the BYPASSRLS pool and
// does NOT call tenant.FromContext. Returns exactly the fields the login use
// case needs: the id (to scope the subsequent user lookup), the status (to
// refuse a suspended tenant), and the session_timeout (to compute session
// expiry). No row when the slug is unknown -> the adapter maps pgx.ErrNoRows to
// ports.ErrTenantNotFound.
func (q *Queries) ResolveTenantBySlug(ctx context.Context, slug string) (ResolveTenantBySlugRow, error) {
	row := q.db.QueryRow(ctx, resolveTenantBySlug, slug)
	var i ResolveTenantBySlugRow
	err := row.Scan(&i.ID, &i.Status, &i.SessionTimeout)
	return i, err
}
