// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, tenant_id, email, password_hash, role, status, must_change_password
FROM users
WHERE tenant_id = $1 AND email = $2
`

type FindUserByEmailParams struct {
	TenantID uuid.UUID
	Email    string
}

type FindUserByEmailRow struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	Email              string
	PasswordHash       string
	Role               string
	Status             string
	MustChangePassword bool
}

// Pre-authentication user lookup (System Design §10 carve-out). Runs on the
// BYPASSRLS pool because login has not yet established a session, so there is no
// authenticated tenant context to bind; the adapter does NOT call
// tenant.FromContext here. The tenant_id is the EXPLICIT first parameter (the
// result of ResolveTenantBySlug), not ambient context — the (tenant_id, email)
// pair is what uniquely identifies the row via users_email_per_tenant_unique,
// which is what makes the explicit-argument scoping correct and safe. Returns
// password_hash for the verification step plus role / status /
// must_change_password for the login decision. No row -> the adapter maps
// pgx.ErrNoRows to ports.ErrUserNotFound.
func (q *Queries) FindUserByEmail(ctx context.Context, arg FindUserByEmailParams) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, arg.TenantID, arg.Email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
	)
	return i, err
}
